[build]
  publish = "/"
  command = ""

# Single Page App (SPA) fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Identity redirects (simplified)
[[redirects]]
  from = "/identity"
  to = "/.netlify/identity"
  status = 200

[[redirects]]
  from = "/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://identity.netlify.com https://unpkg.com; script-src 'self' https://identity.netlify.com https://unpkg.com 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
