[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/identity"
  to = "https://dapper-kitten-079eb9.netlify.app/.netlify/identity"
  status = 200

[[redirects]]
  from = "/.netlify/identity/*"
  to = "https://dapper-kitten-079eb9.netlify.app/.netlify/identity/:splat"
  status = 200

  [[redirects]]
  from = "/accept-invite/*"
  to = "/#invite_token=:splat"
  status = 301

[[redirects]]
  from = "/confirm-invite/*"
  to = "/#confirmation_token=:splat"
  status = 301

[[redirects]]
  from = "/.netlify/identity/*"
  to = "https://dapper-kitten-079eb9.netlify.app/.netlify/identity/:splat"
  status = 200

[[redirects]]
  from = "/accept"
  to = "/#invite_token=:splat"
  status = 301
