backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} '{{slug}}'"
    update: "Update {{collection}} '{{slug}}'"
    delete: "Delete {{collection}} '{{slug}}'"
    uploadMedia: "Upload '{{path}}'"
    deleteMedia: "Delete '{{path}}'"

# Media storage
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# Collections
collections:
  - name: "projects"
    label: "Projects"
    folder: "_data/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Video Link", name: "video_link", widget: "string", hint: "Google Drive embed link" }
      - { label: "Category", name: "category", widget: "select", options: ["short", "long", "reels"] }
      - { label: "Tags", name: "tags", widget: "list", default: ["short"], field: { label: "Tag", name: "tag", widget: "string" } }

  - name: "testimonials"
    label: "Testimonials"
    folder: "_data/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Content", name: "content", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - { label: "Rating", name: "rating", widget: "number", value_type: "int", min: 1, max: 5, default: 5 }