backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_data/projects"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "thumbnail", label: "Thumbnail", widget: "image" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "video_link", label: "Video Link", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["short", "long", "reels"] }

  - name: "testimonials"
    label: "Testimonials"
    folder: "_data/testimonials"
    create: true
    fields:
      - { name: "content", label: "Content", widget: "text" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "role", label: "Role", widget: "string" }
      - { name: "avatar", label: "Avatar", widget: "image" }
